image: node:8.11.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - yarn_cache/

stages:
  - setup
  - test
  - build


lint:
  stage: setup
  before_script:
    - npm install
    - npm install -g eslint
  script:
    - npm run lint

unit_test_cov:
  stage: setup
  before_script:
    - npm install
    # - npm install -g karma webpack karma-webpack karma-jasmine jasmine-core karma-es6-shim karma-mocha-reporter
  script:
    - npm run test
